openapi: 3.0.0
info:
  title: Common Fate Remote Configuration
  version: "1.0"
  contact:
    name: Common Fate
    url: "https://commonfate.io"
  description: "An API for loading deployment configuration, such as installed Access Providers and notifications settings."
servers:
  - url: "http://localhost:6565"
paths:
  /api/v1/config:
    get:
      summary: Get Deployment Configuration
      tags: []
      responses:
        "200":
          $ref: "#/components/responses/DeploymentConfigResponse"
      operationId: get-config
      description: Get deployment configuration.
  /api/v1/config/providers:
    put:
      summary: Update Access Provider configuration
      operationId: update-provider-configuration
      responses:
        "200":
          description: OK
      description: |-
        Writes Access Provider configuration to the remote backend.

        Note: we're considering removing this API endpoint in a future version - this is currently in use because the Approvals dashboard provides a guided setup flow to setup Access Providers. If this setup flow is shifted to a different service, the Approvals API will no longer write Access Provider configuration back to the remote configuration backend.
      requestBody:
        $ref: "#/components/requestBodies/UpdateProvidersRequest"
components:
  schemas:
    DeploymentConfiguration:
      title: DeploymentConfiguration
      x-stoplight:
        id: i1tvp3xdvhkcd
      type: object
      description: The configuration for a Common Fate deployment.
      properties:
        providerConfiguration:
          $ref: "#/components/schemas/ProviderMap"
        notificationsConfiguration:
          $ref: "#/components/schemas/NotificationsConfiguration"
      required:
        - providerConfiguration
        - notificationsConfiguration
    ProviderConfiguration:
      title: ProviderConfiguration
      x-stoplight:
        id: q5ork77yo7qd4
      type: object
      properties:
        uses:
          type: string
        with:
          type: object
          x-go-type: "map[string]string"
      required:
        - uses
        - with
      description: Configuration settings for an individual Access Provider.
    ProviderMap:
      title: ProviderMap
      x-stoplight:
        id: 9oc2srtj185zb
      type: object
      additionalProperties:
        $ref: "#/components/schemas/ProviderConfiguration"
      description: Configuration of all Access Providers.
    NotificationsConfiguration:
      title: NotificationsConfiguration
      x-stoplight:
        id: rnaw9z0bzz24m
      type: object
      description: Notifications configuration for the deployment.
      properties:
        slack:
          $ref: "#/components/schemas/SlackConfiguration"
        slackIncomingWebhooks:
          type: object
          x-go-type: "map[string]map[string]string"
    SlackConfiguration:
      title: SlackConfiguration
      x-stoplight:
        id: eqg2pz843590a
      type: object
      properties:
        apiToken:
          type: string
          description: "The Slack API token. Should be a reference to secret in `awsssm://` format."
      required:
        - apiToken
      description: The Slack notification configuration.
  responses:
    DeploymentConfigResponse:
      description: The configuration of this Common Fate deployment.
      content:
        application/json:
          schema:
            properties:
              deploymentConfiguration:
                $ref: "#/components/schemas/DeploymentConfiguration"
            required:
              - deploymentConfiguration
  requestBodies:
    UpdateProvidersRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              providerConfiguration:
                $ref: "#/components/schemas/ProviderMap"
            required:
              - providerConfiguration
