openapi: 3.0.0
info:
  title: Granted Remote Configuration
  version: '1.0'
  contact:
    name: Common Fate
    url: 'https://commonfate.io'
  description: 'An API for loading deployment configuration, such as installed Access Providers and notifications settings.'
servers:
  - url: 'http://localhost:6565'
paths:
  /api/v1/config:
    get:
      summary: Get Deployment Configuration
      tags: []
      responses: {}
      operationId: get-config
      description: Get deployment configuration.
      requestBody:
        $ref: '#/components/requestBodies/DeploymentConfigResponse'
  /api/v1/config/providers:
    put:
      summary: Update Access Provider configuration
      operationId: update-provider-configuration
      responses:
        '200':
          description: OK
      description: |-
        Writes Access Provider configuration to the remote backend.

        Note: we're considering removing this API endpoint in a future version - this is currently in use because the Approvals dashboard provides a guided setup flow to setup Access Providers. If this setup flow is shifted to a different service, the Approvals API will no longer write Access Provider configuration back to the remote configuration backend.
components:
  schemas:
    DeploymentConfiguration:
      title: DeploymentConfiguration
      x-stoplight:
        id: i1tvp3xdvhkcd
      type: object
      description: The configuration for a Granted Approvals deployment.
      properties:
        providerConfiguration:
          $ref: '#/components/schemas/ProviderMap'
    ProviderConfiguration:
      title: ProviderConfiguration
      x-stoplight:
        id: q5ork77yo7qd4
      type: object
      properties:
        uses:
          type: string
        with:
          type: object
      required:
        - uses
        - with
      description: Configuration settings for an individual Access Provider.
    ProviderMap:
      title: ProviderMap
      x-stoplight:
        id: 9oc2srtj185zb
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ProviderConfiguration'
      description: Configuration of all Access Providers.
  requestBodies:
    DeploymentConfigResponse:
      content:
        application/json:
          schema:
            type: object
            properties:
              deploymentConfiguration:
                $ref: '#/components/schemas/DeploymentConfiguration'
            required:
              - deploymentConfiguration
      description: The configuration of this Granted Approvals deployment.
