package: governance
generate:
  chi-server: true
  models: true
  client: true
  embedded-spec: true
output-options:
  skip-prune: true
output: governance/pkg/types/api.gen.go
import-mapping:
  ./openapi.yml: github.com/common-fate/common-fate/pkg/types
  ./accesshandler/openapi.yml: github.com/common-fate/common-fate/accesshandler/pkg/types
