version: 2
deployment:
  stackName: common-fate-jack-nov
  account: "616777145260"
  region: ap-southeast-2
  release: ""
  dev: true
  parameters:
    CognitoDomainPrefix: new
    AdministratorGroupID: common_fate_administrators
    ProviderConfiguration:
      aws-sso-v2:
        uses: commonfate/aws-sso@v2
        with:
          identityStoreId: d-976708da7d
          instanceArn: arn:aws:sso:::instance/ssoins-825968feece9a0b6
          region: ap-southeast-2
          ssoRoleArn: arn:aws:iam::632700053629:role/Granted-Access-Handler-SS-GrantedAccessHandlerSSOR-J3EE9BM8QKBW
          ssoSubdomain: custom-domain
      azure-ad:
        uses: commonfate/azure-ad@v1
        with:
          clientId: 089723ea-8a48-410c-9acc-fab919ce2ae5
          clientSecret: awsssm:///granted/providers/azure-ad/clientSecret:4
          tenantId: 0d928b90-2449-4c9e-90cc-acce6171ad53
      testgroups:
        uses: commonfate/testgroups@v1
        with:
          groups: a,b,c,d,e,f,g
      testvault:
        uses: commonfate/testvault@v1
        with:
          apiUrl: https://prod.testvault.granted.run
          uniqueId: 2CBsuomHFRE3mrpLGWFaxbyKXG6
    NotificationsConfiguration:
      slackIncomingWebhooks:
        -general:
          webhookUrl: awsssm:///granted/secrets/notifications/slackIncomingWebhooks/-general/webhookUrl:1
