package: governance
generate:
  chi-server: true
  models: true
  client: true
  embedded-spec: true
output-options:
  skip-prune: true
output: api.gen.go
import-mapping:
  ../openapi.yml: github.com/common-fate/granted-approvals/pkg/types
