name: Format

on:
  push:
    # main has branch protection, so we can't run formatting there.
    branches-ignore:
      - main

jobs:
  prettier:
    name: OpenAPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      # https://github.com/creyD/prettier_action/issues/114
      - name: Install npm v8
        run: npm i -g npm@8

      - name: Prettify code
        uses: common-fate/prettier-action@6602189cf8bac1ce73ffe601925f6127ab7f21ac
        with:
          prettier_options: --write openapi.yml
          commit_message: "CI: auto-formatted openapi.yml"

      - name: Prettify Access Handler code
        uses: common-fate/prettier-action@6602189cf8bac1ce73ffe601925f6127ab7f21ac
        with:
          prettier_options: --write accesshandler/openapi.yml
          commit_message: "CI: auto-formatted accesshandler/openapi.yml"
